server:
  port: 8761
eureka:
  server:
    #关闭自我保护机制
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    #申明这是一个服务端，不注册自己
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server